spring.application.name=demo
server.port=8081

spring.security.oauth2.resourceserver.jwt.issuer-uri=${KEYCLOAK_ISSUER_URI}
spring.security.oauth2.client.provider.keycloak.issuer-uri=${KEYCLOAK_ISSUER_URI}
spring.security.oauth2.client.registration.keycloak.client-id=reports-frontend
spring.security.oauth2.client.registration.keycloak.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.keycloak.redirect-uri=http://localhost:3000

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.oauth2=DEBUG